apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-dev
  labels:
    app: kubernetes-dev
spec:
  selector:
    matchLabels:
      app: kubernetes-dev
  template:
    metadata:
      labels:
        app: kubernetes-dev
    spec:
      containers:
      - name: kubernetes-dev
        image: alicek106/ubuntu-golang:18.04-1.13-slim
        ports:
        - containerPort: 22
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dev-svc
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 30000
  selector:
    app: kubernetes-dev
  type: NodePort
